/**
 * Libertas Design System - Font Loading
 *
 * Loads Google Fonts using @remotion/google-fonts for type-safe,
 * render-blocking font loading.
 *
 * Fonts (from SPEC.md):
 * - Space Grotesk: Display headlines (Bold 700)
 * - Inter: Body text (Regular 400, Bold 700)
 * - JetBrains Mono: Terminal/code (Regular 400, Medium 500)
 */

import { loadFont as loadSpaceGrotesk } from "@remotion/google-fonts/SpaceGrotesk";
import { loadFont as loadInter } from "@remotion/google-fonts/Inter";
import { loadFont as loadJetBrainsMono } from "@remotion/google-fonts/JetBrainsMono";

// =============================================================================
// LOAD FONTS WITH SPECIFIC WEIGHTS
// =============================================================================

/**
 * Space Grotesk - Display headlines, hero text, section titles
 * Weight: Bold (700)
 */
const spaceGrotesk = loadSpaceGrotesk("normal", {
  weights: ["700"],
  subsets: ["latin"],
});

/**
 * Inter - Readable body copy
 * Weights: Regular (400), Bold (700) for captions
 */
const inter = loadInter("normal", {
  weights: ["400", "700"],
  subsets: ["latin"],
});

/**
 * JetBrains Mono - Terminal sequences, commands, code, data labels
 * Weights: Regular (400), Medium (500)
 */
const jetBrainsMono = loadJetBrainsMono("normal", {
  weights: ["400", "500"],
  subsets: ["latin"],
});

// =============================================================================
// EXPORTED FONT FAMILIES
// =============================================================================

/**
 * Font family strings ready for use in style props.
 * These include proper fallbacks generated by @remotion/google-fonts.
 */
export const fontFamilies = {
  /** Display headlines - Space Grotesk Bold */
  display: spaceGrotesk.fontFamily,

  /** Body text - Inter */
  body: inter.fontFamily,

  /** Terminal/code - JetBrains Mono */
  mono: jetBrainsMono.fontFamily,
} as const;

// =============================================================================
// WAIT FOR FONTS TO LOAD
// =============================================================================

/**
 * Wait for all fonts to finish loading.
 * Useful if you need to ensure fonts are ready before measuring text.
 */
export async function waitForFonts(): Promise<void> {
  await Promise.all([
    spaceGrotesk.waitUntilDone(),
    inter.waitUntilDone(),
    jetBrainsMono.waitUntilDone(),
  ]);
}

// =============================================================================
// FONT STYLE HELPERS
// =============================================================================

/**
 * Get complete style object for display text (headlines, titles)
 */
export function displayStyle(fontSize: number = 72) {
  return {
    fontFamily: fontFamilies.display,
    fontWeight: 700,
    fontSize,
  } as const;
}

/**
 * Get complete style object for body text
 */
export function bodyStyle(fontSize: number = 32, bold: boolean = false) {
  return {
    fontFamily: fontFamilies.body,
    fontWeight: bold ? 700 : 400,
    fontSize,
  } as const;
}

/**
 * Get complete style object for terminal/code text
 */
export function terminalStyle(fontSize: number = 32) {
  return {
    fontFamily: fontFamilies.mono,
    fontWeight: 400,
    fontSize,
  } as const;
}

/**
 * Get complete style object for data labels (scores, timestamps)
 */
export function dataStyle(fontSize: number = 24) {
  return {
    fontFamily: fontFamilies.mono,
    fontWeight: 500,
    fontSize,
  } as const;
}

export default fontFamilies;
